export const MASK_TYPE = {
  DATE: 'date',
  DATE_TIME: 'date_time',
  CURRENCY: 'currency',
  CPF: 'cpf',
  CNPJ: 'cnpj',
  TEXT: 'string',
  NUMBER: 'number',
  DECIMAL: 'decimal',
  MASK: 'mask',
  PARTIAL_MASK: 'partial_mask',
  PERCENT: 'percent',
  OBJECT: 'object',
  LOCATION: 'location',
};

export const R = {
  ERROR_MESSAGE: {
    GENERIC_HTTP_ERROR: 'Erro ao comunicar com o servidor, verifique sua conexão e tente novamente em alguns segundos.',
    GENERIC_LOGIN_EXCEPTION: `Erro ao efetuar o login no sistema`,
    GPS_ERROR: 'Erro: Favor habilitar a localização do seu navegador.',
    NOT_AUTORIZED: 'Acesso negado!',
    TOO_MANY_LOGIN_ATTEMPTS: 'Muitas tentativas de login sucetivas. Aguarde alguns minutos e tente novamente.',
    QUOTA_EXCEEDED: 'Você gastou sua cota de acesso a este recurso, você pode continuar navegando pelas demais funcionalidades.',
  },
  ERROR_TYPE: {
  },
  REQUEST_HEADERS: {
    ACCESS_TOKEN: 'x-access-token',
    DEVICE_ID: 'x-device-id',
    DEVICE_LOCATION: 'x-device-location',
  },
  KEYS: {
    REDIRECT: 'redirect',
  },
  FIELDS: {
    INCREMENTAL_SIMPLE_LIST: {
      ADD_FILED: 'Descrição do Item',
    },
    PT_PAGINATOR_INTL: {
      NEXTPAGE_LABEL: 'Próxima Página',
      PREVIOUSPAGE_LABEL: 'Página Anterior',
      ITEMSPERPAGE_LABEL: 'Itens por página:',
      FROM_LABEL: 'de',
    }
  },
  DATA: {
    TRANSLATION: {
      NAME: 'Nome',
      DATE: 'Data',
      CONTRACT: 'Contrato',
      CLIENTDOCUMENT: 'Documento',
      CLIENTNAME: 'Cliente',
      AMOUNT: 'Valor',
      TAC: 'TAC',
      IOC: 'IOC',
      WARRANTY: 'Garantia',
      OFFICE: 'Filial',
      OFFICENAME: 'Nome da Filial',
      OFFICEDOCUMENT: 'CNPJ da Filial',
      PLAN: 'Plano',
      FIRSTDUEDATE: 'Data da Primeira Parcela',
      COMPAYNAME: 'Nome da Loja',
      CONTRACTDATE: 'Data de Contratação',
      APROVALDATE: 'Data de Aprovação',
      TABLECODE: 'Tabela',
      CONTRACTSTATUS: 'Situação do Contrato',
      FUNDINGAMOUNT: 'Valor Financiado',
      INSURANCEPRICE: 'Valor do Seguro',
      INSTALLMENT: 'Prestação',
      DUEDATE: 'Data de Vencimento',
      PAYMENTDATE: 'Data de Pagamento',
      INSTALLMENTSTATUS: 'Situação da Parcela',
      WRITEOFFTYPE: 'Natureza da Baixa',
      DAYSOFDELAY: 'Dias de Atraso',
      INSTALLMENTAMOUNT: 'Valor da Prestação',
      GRACEPERIOD: 'Carência',
      OPERATINGRATE: 'Taxa de Operação',
      FUNDINGRATE: 'Taxa de Funding',
      PMTFUNDINGRATE: 'PMT Taxa de Funding',
      AMOUNTPAID: 'Valor Pago',
      EQUALIZATION: 'Equalização',
      ACCESSEDAT: 'Data do Acesso',
      RESOURCE: 'Recurso',
      QUERY: 'Condições de Filtro',
      USERNAME: 'Nome do Usuário',
      USEREMAIL: 'Email',
      USERDEVICE: 'Identificação do Dispositivo',
      USERLOCATION: 'Localização do Dispositivo',
    },
    MASK: {
      TYPES: MASK_TYPE,
      NAME: MASK_TYPE.TEXT,
      DATE: MASK_TYPE.DATE,
      CONTRACT: MASK_TYPE.TEXT,
      CLIENTDOCUMENT: MASK_TYPE.CPF,
      CLIENTNAME: MASK_TYPE.TEXT,
      AMOUNT: MASK_TYPE.CURRENCY,
      TAC: MASK_TYPE.CURRENCY,
      IOC: MASK_TYPE.CURRENCY,
      WARRANTY: MASK_TYPE.CURRENCY,
      OFFICE: MASK_TYPE.NUMBER,
      OFFICENAME: MASK_TYPE.TEXT,
      OFFICEDOCUMENT: MASK_TYPE.CNPJ,
      PLAN: MASK_TYPE.NUMBER,
      FIRSTDUEDATE: MASK_TYPE.DATE,
      COMPAYNAME: MASK_TYPE.TEXT,
      CONTRACTDATE: MASK_TYPE.DATE,
      APROVALDATE: MASK_TYPE.DATE,
      TABLECODE: MASK_TYPE.TEXT,
      CONTRACTSTATUS: MASK_TYPE.TEXT,
      FUNDINGAMOUNT: MASK_TYPE.CURRENCY,
      INSURANCEPRICE: MASK_TYPE.CURRENCY,
      INSTALLMENT: MASK_TYPE.NUMBER,
      DUEDATE: MASK_TYPE.DATE,
      PAYMENTDATE: MASK_TYPE.DATE,
      INSTALLMENTSTATUS: MASK_TYPE.TEXT,
      WRITEOFFTYPE: MASK_TYPE.TEXT,
      DAYSOFDELAY: MASK_TYPE.NUMBER,
      INSTALLMENTAMOUNT: MASK_TYPE.CURRENCY,
      GRACEPERIOD: MASK_TYPE.NUMBER,
      OPERATINGRATE: MASK_TYPE.PERCENT,
      FUNDINGRATE: MASK_TYPE.PERCENT,
      PMTFUNDINGRATE: MASK_TYPE.CURRENCY,
      AMOUNTPAID: MASK_TYPE.CURRENCY,
      EQUALIZATION: MASK_TYPE.CURRENCY,
      ACCESSEDAT: MASK_TYPE.DATE_TIME,
      RESOURCE: MASK_TYPE.TEXT,
      QUERY: MASK_TYPE.OBJECT,
      USERNAME: MASK_TYPE.TEXT,
      USEREMAIL: MASK_TYPE.TEXT,
      USERDEVICE: MASK_TYPE.TEXT,
      USERLOCATION: MASK_TYPE.LOCATION,
    },
  },
  OK: 'OK',
};
