export const MASK_TYPE = {
  DATE: 'date',
  DATE_TIME: 'date_time',
  CURRENCY: 'currency',
  CPF: 'cpf',
  CNPJ: 'cnpj',
  TEXT: 'string',
  NUMBER: 'number',
  DECIMAL: 'decimal',
  MASK: 'mask',
  PARTIAL_MASK: 'partial_mask',
  PERCENT: 'percent',
  OBJECT: 'object',
  LOCATION: 'location',
};

export const R = {
  ERROR_MESSAGE: {
    GENERIC_HTTP_ERROR: 'Server communication error. Check your connection and try again in few minutes.',
    GENERIC_LOGIN_EXCEPTION: `Login error`,
    GPS_ERROR: 'Error: Please, allow the application to get location on your browser.',
    NOT_AUTORIZED: 'Access Denied!',
    TOO_MANY_LOGIN_ATTEMPTS: 'Too many logins attempts. Try againg in few minutes.',
    QUOTA_EXCEEDED: 'You reached your quota for this specific resource, but you can navigate to other resources.',
  },
  ERROR_TYPE: {
  },
  REQUEST_HEADERS: {
    ACCESS_TOKEN: 'x-access-token',
    DEVICE_ID: 'x-device-id',
    DEVICE_LOCATION: 'x-device-location',
  },
  KEYS: {
    REDIRECT: 'redirect',
  },
  FIELDS: {
    INCREMENTAL_SIMPLE_LIST: {
      ADD_FILED: 'Item description',
    },
    PT_PAGINATOR_INTL: {
      NEXTPAGE_LABEL: 'Next page',
      PREVIOUSPAGE_LABEL: 'Previous page',
      ITEMSPERPAGE_LABEL: 'Itens per page:',
      FROM_LABEL: 'from',
    }
  },
  DATA: {
    TRANSLATION: {
      NAME: 'Name',
      DATE: 'Date',
      CONTRACT: 'Contract',
      CLIENTDOCUMENT: 'Document',
      CLIENTNAME: 'Client',
      AMOUNT: 'Amount',
      TAC: 'TAC',
      IOC: 'IOC',
      WARRANTY: 'Warranty',
      OFFICE: 'Office',
      OFFICENAME: 'Office Name',
      OFFICEDOCUMENT: 'Office Document',
      PLAN: 'Plan',
      FIRSTDUEDATE: 'First due date',
      COMPAYNAME: 'Company name',
      CONTRACTDATE: 'Contract Date',
      APROVALDATE: 'Aproval Date',
      TABLECODE: 'Table',
      CONTRACTSTATUS: 'Status',
      FUNDINGAMOUNT: 'Funding',
      INSURANCEPRICE: 'Insurance',
      INSTALLMENT: 'Installment',
      DUEDATE: 'Due Date',
      PAYMENTDATE: 'Payment',
      INSTALLMENTSTATUS: 'Installment Status',
      WRITEOFFTYPE: 'Write Off',
      DAYSOFDELAY: 'Delay',
      INSTALLMENTAMOUNT: 'Installment Amoount',
      GRACEPERIOD: 'Grace Period',
      OPERATINGRATE: 'Rate',
      FUNDINGRATE: 'Funding Rate',
      PMTFUNDINGRATE: 'PMT over Funding Rate',
      AMOUNTPAID: 'Paid',
      EQUALIZATION: 'Equalization',
      ACCESSEDAT: 'Access',
      RESOURCE: 'Resource',
      QUERY: 'Query',
      USERNAME: 'User Name',
      USEREMAIL: 'Email',
      USERDEVICE: 'Device',
      USERLOCATION: 'Localização',
    },
    MASK: {
      TYPES: MASK_TYPE,
      NAME: MASK_TYPE.TEXT,
      DATE: MASK_TYPE.DATE,
      CONTRACT: MASK_TYPE.TEXT,
      CLIENTDOCUMENT: MASK_TYPE.CPF,
      CLIENTNAME: MASK_TYPE.TEXT,
      AMOUNT: MASK_TYPE.CURRENCY,
      TAC: MASK_TYPE.CURRENCY,
      IOC: MASK_TYPE.CURRENCY,
      WARRANTY: MASK_TYPE.CURRENCY,
      OFFICE: MASK_TYPE.NUMBER,
      OFFICENAME: MASK_TYPE.TEXT,
      OFFICEDOCUMENT: MASK_TYPE.CNPJ,
      PLAN: MASK_TYPE.NUMBER,
      FIRSTDUEDATE: MASK_TYPE.DATE,
      COMPAYNAME: MASK_TYPE.TEXT,
      CONTRACTDATE: MASK_TYPE.DATE,
      APROVALDATE: MASK_TYPE.DATE,
      TABLECODE: MASK_TYPE.TEXT,
      CONTRACTSTATUS: MASK_TYPE.TEXT,
      FUNDINGAMOUNT: MASK_TYPE.CURRENCY,
      INSURANCEPRICE: MASK_TYPE.CURRENCY,
      INSTALLMENT: MASK_TYPE.NUMBER,
      DUEDATE: MASK_TYPE.DATE,
      PAYMENTDATE: MASK_TYPE.DATE,
      INSTALLMENTSTATUS: MASK_TYPE.TEXT,
      WRITEOFFTYPE: MASK_TYPE.TEXT,
      DAYSOFDELAY: MASK_TYPE.NUMBER,
      INSTALLMENTAMOUNT: MASK_TYPE.CURRENCY,
      GRACEPERIOD: MASK_TYPE.NUMBER,
      OPERATINGRATE: MASK_TYPE.PERCENT,
      FUNDINGRATE: MASK_TYPE.PERCENT,
      PMTFUNDINGRATE: MASK_TYPE.CURRENCY,
      AMOUNTPAID: MASK_TYPE.CURRENCY,
      EQUALIZATION: MASK_TYPE.CURRENCY,
      ACCESSEDAT: MASK_TYPE.DATE_TIME,
      RESOURCE: MASK_TYPE.TEXT,
      QUERY: MASK_TYPE.OBJECT,
      USERNAME: MASK_TYPE.TEXT,
      USEREMAIL: MASK_TYPE.TEXT,
      USERDEVICE: MASK_TYPE.TEXT,
      USERLOCATION: MASK_TYPE.LOCATION,
    },
  },
  OK: 'OK',
};
